[env]
_.path = "target/debug"

[tasks.test]
run = [
  "cargo nextest run",
  "git submodule update --init --recursive",
  "test/bats/bin/bats test",
]

[tasks.ci]
depends = ["lint", "build", "docs:build", "test"]

[tasks."docs:build"]
dir = "docs"
run = "aube install && exec aube run docs:build"

[tasks.docs]
dir = "docs"
run = "aube install && exec aube run docs:dev"

[tasks.lint]
run = "hk check --all"

[tasks.lint-fix]
run = "hk fix --all"

[tasks.build]
run = "cargo build"

[tasks.render]
depends = ["build"]
run = [
  "pitchfork usage > pitchfork.usage.kdl",
  "rm -rf docs/cli && mkdir -p docs/cli",
  "usage g markdown -mf pitchfork.usage.kdl --out-dir docs/cli --url-prefix /cli",
  "usage g json -f pitchfork.usage.kdl > docs/cli/commands.json",
  "pitchfork schema > docs/public/schema.json",
  "git add pitchfork.usage.kdl docs",
]

[tasks.install-dev]
env = { "PITCHFORK_LOG" = "debug" }
run = [
  "cargo install --path . --debug",
  "pitchfork sup start -f",
]

[tools]
aube = "latest"
bun = "latest" # for tests
cargo-binstall = "latest"
communique = "latest"
hk = "latest"
node = "24"
pkl = "latest"
usage = "latest" # for rendering CLI usage
"cargo:cargo-nextest" = "latest"
